name: watch-hub-restapi

services:
  web:
    build: .
    volumes:
      - ./project:/var/www/html
    ports:
      - 80:80
  db:
    image: mysql
    volumes:
      - ./db_data/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: watch_hub_db
    ports:
      - 3306:3306
